Make bootstrap script to run for both mac and linux

diff --git a/.config/yadm/bootstrap b/.config/yadm/bootstrap
--- a/.config/yadm/bootstrap
+++ b/.config/yadm/bootstrap
@@ -1,155 +1,163 @@
-#!/bin/bash
+#!/bin/sh
 
-# Add a new non-sudo user
-sudo adduser praveen
+# Utility Function to install packages
+install_packages() {
+  packages=("$@")
 
-# Install necessary packages
-sudo apt update
-# Install necessary packages 
-packages=(
-  git
-  build-essential
-  libssl-dev
-  libreadline-dev
-  zlib1g-dev
-  python3
-  python3-pip
-  nodejs
-  yarn
-  yadm
-  bat
-  fd-find
-  fzf
-  ripgrep
-  tree
-  universal-ctags
-  imagemagick
-  shared-mime-inof
-  zip
-  unzip
-)
+  for package in "${packages[@]}"; do
+    if ! dpkg -s "$package" >/dev/null 2>&1; then
+      sudo apt install -y "$package"
+    else
+      echo "$package is already installed"
+    fi
+  done
+}
 
-for package in "${packages[@]}"; do
-  if ! dpkg -s "$package" >/dev/null 2>&1; then
-    sudo apt install -y "$package"
-  else
-    echo "$package is already installed"
-  fi
-done
-
-optional_packages=(
-  libsqlite3-dev
-  postgresql-13
-  postgresql-client-13
-  redis-server
-  apt-transport-https
-  elasticsearch=7.10.2
-  kibana=7.10.2
-)
-
-for package in "${optional_packages[@]}"; do
-	read -p "$package is not installed. Do you want to install it? (y/n)" choice 
-	case "$choice" in 
-	  y|Y ) sudo apt install -y "$package";; 
-	  n|N ) echo "Skipping $package";; 
-	  * ) echo "Invalid choice. Skipping $package";; 
-	esac
-done
-
-# Install Node.js (optional)
-if ! command -v node &> /dev/null; then
-  curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
-  sudo apt install -y nodejs
-else
-  echo "Node is already installed"
-fi
-
-# Install RVM and Ruby
-if ! command -v rvm &> /dev/null; then
-  curl -sSL https://rvm.io/mpapis.asc | gpg --import -
-  curl -sSL https://rvm.io/pkuczynski.asc | gpg --import -
-  curl -sSL https://get.rvm.io | bash -s stable --ruby
-  source ~/.rvm/scripts/rvm
-  rvm install 2.7.6
-else
-  echo "RVM is already installed"
-fi
-
-# Set up PostgreSQL for user praveen
-if ! sudo -u postgres psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='praveen'" | grep -q 1; then 
-  sudo -u postgres createuser -s praveen 
-  sudo -u postgres createdb praveen 
-  sudo su - postgres -c "psql -c \"GRANT ALL PRIVILEGES ON DATABASE praveen TO praveen;\""
-else
-  echo "PostgreSQL is already configured for praveen user"
-fi
+SYSTEM_TYPE=$(uname -s)
 
 # Install Oh My Zsh (optional)
-if [[ ! -d ~/.oh-my-zsh ]]; then 
-  sudo apt install -y zsh 
+if [ ! -d ~/.oh-my-zsh ]; then
   sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
-  git clone https://github.com/spaceship-prompt/spaceship-prompt.git "$ZSH_CUSTOM/themes/spaceship-prompt" --depth=1
-  ln -s "$ZSH_CUSTOM/themes/spaceship-prompt/spaceship.zsh-theme" "$ZSH_CUSTOM/themes/spaceship.zsh-theme"
 fi
 
-# Install Overmind
-uname=$(uname -s)
+# MAC Specific setup
+if [ "$SYSTEM_TYPE" == "Darwin" ]; then
+  # Install homebrew if it's missing
+  if ! command -v brew >/dev/null 2>&1; then
+    echo "Installing homebrew"
+    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+  fi
 
-if [[ "$uname" == "Linux" ]] ; then
-  if ! command -v overmind &> /dev/null; then
-    curl https://github.com/DarthSim/overmind/releases/download/v2.2.2/overmind-v2.2.2-linux-amd64.gz
-    gzip overmind-v2.2.2-linux-amd64.gz -d
-    sudo mv overmind-v2.2.2-linux-amd64 /usr/local/bin/overmind
-    chmod a+x /usr/local/bin/overmind
-  else
-    echo "Overmind is already installed"
+  if [ -f "$HOME/config/brewfile/.Brewfile" ]; then
+    echo "Updating homebrew bundle"
+    brew bundle --file="$HOME/config/brewfile/.Brewfile"
   fi
 fi
 
-# Set up Git
-# git config --global user.name "Your Name"
-# git config --global user.email "your.email@example.com"
+# Linux specific setup
+if [[ "$SYSTEM_TYPE" == "Linux" ]] ; then
+  # Add a new non-sudo user
+  sudo adduser praveen
 
-# Install yadm and clone dotfiles repository
-yadm clone https://github.com/praveendhawan/dotfiles
+  # Install necessary packages
+  sudo apt update
+  # Install necessary packages 
+  packages=(
+    git
+    build-essential
+    libssl-dev
+    libreadline-dev
+    zlib1g-dev
+    python3
+    python3-pip
+    shared-mime-info
+    zip
+    unzip
+    zsh
+  )
 
+  install_packages "${packages[@]}"
 
-# Install neovim
-if ! command -v nvim &> /dev/null; then
-  sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
-  test -d ~/.linuxbrew && eval "$(~/.linuxbrew/bin/brew shellenv)"
-  echo 'eval $(~/.linuxbrew/bin/brew shellenv)' >>~/.profile
-  brew install neovim
-else
-  echo "Neovim is already installed"
+  # install linuxbrew
+  if ! command -v brew >/dev/null 2>&1; then
+    echo "Installing homebrew"
+    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+
+    test -d ~/.linuxbrew && eval "$(~/.linuxbrew/bin/brew shellenv)"
+
+    if [ -f "$HOME/config/brewfile/.Brewfile" ]; then
+      echo "Updating homebrew bundle"
+      brew bundle --file="$HOME/config/brewfile/.Brewfile"
+    fi
+  fi
+
+  install_packages packages
+
+  optional_packages=(
+    libsqlite3-dev
+    postgresql-13
+    postgresql-client-13
+    redis-server
+    apt-transport-https
+    elasticsearch=7.10.2
+    kibana=7.10.2
+  )
+
+  for package in "${optional_packages[@]}"; do
+    read -p "$package is not installed. Do you want to install it? (y/n)" choice 
+    case "$choice" in 
+      y|Y ) sudo apt install -y "$package";; 
+      n|N ) echo "Skipping $package";; 
+      * ) echo "Invalid choice. Skipping $package";; 
+    esac
+  done
 fi
 
-# Install NvChad 
-git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1
+# OS agnostic setup
+#
+# NODE JS 
+read -p "Do you want to install nodejs" choice
+INSTALL_NODE=false
+case "$choice" in
+  y|Y) INSTALL_NODE=true;;
+  *) echo "Skipping nodejs installation";;
+esac
 
-# Add customization for Nvchad
-ln -s ~/.config/nvim_custom ~/.config/nvim/lua/custom
+if $INSTALL_NODE; then
+  if ! command -v nvm >/dev/null 2>&1; then
+    echo "Installing nvm"
+    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.4/install.sh | bash
+  fi
+  # Load nvm
+  NVM_DIR="$HOME/.nvm"
+  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
+  # Install nodejs via nvm
+  nvm install node
+fi
 
-nvim
+# RVM
+read -p "Do you want to install rvm" choice
+INSTALL_RUBY=false
+case "$choice" in
+  y|Y ) INSTALL_RUBY = 1;;
+  * ) echo "Skipping ruby installation";;
+esac
 
+if $INSTALL_RUBY; then
+  if ! command -v rvm &> /dev/null 2>&1; then
+    curl -sSL https://rvm.io/mpapis.asc | gpg --import -
+    curl -sSL https://rvm.io/pkuczynski.asc | gpg --import -
+    curl -sSL https://get.rvm.io | bash -s stable --ruby
+    source ~/.rvm/scripts/rvm
+    rvm install 2.7.6
+  else
+    echo "RVM is already installed"
+  fi
+fi
+
+# Postgres
+if ! command -v psql &> /dev/null 2>&1; then
+  read -p "Do you want to create a new postgres user" choice
+  case "$choice" in
+    y|Y ) CREATE_POSTGRES_USER = 1;;
+    * ) echo "Skipping postgres user creation";;
+  esac
+
+  if $CREATE_POSTGRES_USER; then
+    read -p "Enter the username: " username
+    if ! sudo -u postgres psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='$username'" | grep -q 1; then 
+      sudo -u postgres createuser -s $username 
+      sudo -u postgres createdb $username
+      sudo su - postgres -c "psql -c \"GRANT ALL PRIVILEGES ON DATABASE $username TO $username;\""
+    else
+      echo "PostgreSQL is already configured for $username user"
+    fi
+  fi
+fi
 
 # Check if fd symlink already exists before creating
 if [ ! -L /usr/local/bin/fd ]; then
   ln -s "$(which fdfind)" /usr/local/bin/fd
-fi
-
-# Instals brewfile content on Mac
-if [[ "$uname" == "Darwin" ]] ; then
-  brew bundle install
-fi
-
-# Check if AWS CLI v2 is already installed before attempting to install
-if [[ "$uname" == "Linux" ]] ; then
-  if ! command -v aws &> /dev/null; then
-    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-    unzip awscliv2.zip
-    sudo ./aws/install
-  fi
 fi
 
 # Check if ctree is already installed before attempting to install
@@ -165,3 +173,12 @@ if [ ! -d "$dir" ]; then
   sudo chmod a+x "$dir/component_tree/bin/ctree"
   export PATH="$PATH:$dir/component_tree/bin"
 fi
+
+# Configure Nvim
+if ! command -v nvim &> /dev/null 2>&1; then
+  brew install neovim
+fi
+
+git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1
+ln -s ~/.config/nvim_custom ~/.config/nvim/lua/custom
+nvim
