Add bootstrap for alpine

diff --git a/.config/yadm/bootstrap b/.config/yadm/bootstrap
--- a/.config/yadm/bootstrap
+++ b/.config/yadm/bootstrap
@@ -1,216 +1,24 @@
-#!/bin/sh
+#!/bin/bash
 
-# Utility Function to install packages
-install_packages() {
-  packages=("$@")
+# Save this file as ~/.config/yadm/bootstrap and make it executable. It will
+# execute all executable files (excluding templates and editor backups) in the
+# ~/.config/yadm/bootstrap.d directory when run.
 
-  for package in "${packages[@]}"; do
-    if ! dpkg -s "$package" >/dev/null 2>&1; then
-      sudo apt install -y "$package"
-    else
-      echo "$package is already installed"
+set -eu
+
+# Directory to look for bootstrap executables in
+BOOTSTRAP_D="${BASH_SOURCE[0]}.d"
+
+if [[ ! -d "$BOOTSTRAP_D" ]]; then
+    echo "Error: bootstrap directory '$BOOTSTRAP_D' not found" >&2
+    exit 1
+fi
+
+find -L "$BOOTSTRAP_D" -type f | sort | while IFS= read -r bootstrap; do
+    if [[ -x "$bootstrap" && ! "$bootstrap" =~ "##" && ! "$bootstrap" =~ "~$" ]]; then
+        if ! "$bootstrap"; then
+            echo "Error: bootstrap '$bootstrap' failed" >&2
+            exit 1
+        fi
     fi
-  done
-}
-
-SYSTEM_TYPE=$(uname -s)
-
-# Install Oh My Zsh (optional)
-if [ ! -d ~/.oh-my-zsh ]; then
-  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
-  # Install Zsh Autosuggestions
-  if [ ! -d ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions ]; then
-    git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
-  fi
-fi
-
-# MAC Specific setup
-if [ "$SYSTEM_TYPE" == "Darwin" ]; then
-  # Install homebrew if it's missing
-  if ! command -v brew >/dev/null 2>&1; then
-    echo "Installing homebrew"
-    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
-  fi
-
-  if [ -f "$HOME/config/brewfile/.Brewfile" ]; then
-    echo "Updating homebrew bundle"
-    brew bundle --file="$HOME/config/brewfile/.Brewfile"
-  fi
-
-  if [ -f "$HOME/config/brewfile/.Brewfile.darwin" ]; then
-    echo "Updating homebrew bundle for mac"
-    brew bundle --file="$HOME/config/brewfile/.Brewfile.darwin"
-  fi
-
-  # force the linking of libpq to avoid issue with installing pg gem
-  if brew list libpq >/dev/null 2>&1; then
-    brew link --force libpq
-  fi
-fi
-
-# Linux specific setup
-if [[ "$SYSTEM_TYPE" == "Linux" ]] ; then
-  # Add a new non-sudo user
-  sudo adduser praveen
-
-  # Install necessary packages
-  sudo apt update
-  # Install necessary packages
-  packages=(
-    git
-    build-essential
-    libssl-dev
-    libreadline-dev
-    zlib1g-dev
-    python3
-    python3-pip
-    zip
-    unzip
-    zsh
-  )
-
-  install_packages "${packages[@]}"
-
-  # install linuxbrew
-  if ! command -v brew >/dev/null 2>&1; then
-    echo "Installing homebrew"
-    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
-
-    test -d ~/.linuxbrew && eval "$(~/.linuxbrew/bin/brew shellenv)"
-
-    if [ -f "$HOME/config/brewfile/.Brewfile" ]; then
-      echo "Updating homebrew bundle"
-      brew bundle --file="$HOME/config/brewfile/.Brewfile"
-    fi
-
-    if [ -f "$HOME/config/brewfile/.Brewfile.linux" ]; then
-      echo "Updating homebrew bundle for linux"
-      brew bundle --file="$HOME/config/brewfile/.Brewfile.linux"
-    fi
-  fi
-
-  install_packages packages
-
-  optional_packages=(
-    libsqlite3-dev
-    postgresql-13
-    postgresql-client-13
-    redis-server
-    apt-transport-https
-    elasticsearch=7.10.2
-    kibana=7.10.2
-  )
-
-  for package in "${optional_packages[@]}"; do
-    read -p "$package is not installed. Do you want to install it? (y/n) > " choice
-    case "$choice" in
-      y|Y ) sudo apt install -y "$package";;
-      n|N ) echo "Skipping $package";;
-      * ) echo "Invalid choice. Skipping $package";;
-    esac
-  done
-
-  # Install nerd fonts
-  if fc-list | grep -i "FiraMono" >/dev/null 2>&1; then
-    echo "FiraMono is already installed"
-  else
-    echo "Installing FiraMono"
-    git clone --filter=blob:none --sparse git@github.com:ryanoasis/nerd-fonts
-    cd nerd-fonts
-    ./install.sh FiraMono
-
-    # cleanup
-    cd ..
-    rm -rf nerd-fonts
-  fi
-fi
-
-# OS agnostic setup
-#
-# NODE JS
-read -p "Do you want to install nodejs > " choice
-INSTALL_NODE=false
-case "$choice" in
-  y|Y) INSTALL_NODE=true;;
-  *) echo "Skipping nodejs installation";;
-esac
-
-if $INSTALL_NODE; then
-  if ! command -v asdf &> /dev/null 2>&1; then
-    brew install asdf
-  fi
-  # Load asdf
-  . $(brew --prefix asdf)/libexec/asdf.sh
-  asdf plugin add nodejs
-  asdf install nodejs latest
-  asdf install nodejs 16.5.0
-  asdf global nodejs 16.5.0
-fi
-
-# RVM
-read -p "Do you want to install rvm > " choice
-INSTALL_RUBY=false
-case "$choice" in
-  y|Y ) INSTALL_RUBY=true;;
-  * ) echo "Skipping ruby installation";;
-esac
-
-if $INSTALL_RUBY; then
-  if ! command -v asdf &> /dev/null 2>&1; then
-    brew install asdf
-  fi
-  # Load asdf
-  . $(brew --prefix asdf)/libexec/asdf.sh
-  asdf plugin add ruby
-  asdf install ruby 2.7.6
-  asdf global ruby 2.7.6
-fi
-
-# Postgres
-if ! command -v psql &> /dev/null 2>&1; then
-CREATE_POSTGRES_USER=false
-  read -p "Do you want to create a new postgres user > " choice
-  case "$choice"
-    y|Y ) CREATE_POSTGRES_USER=1;;
-    * ) echo "Skipping postgres user creation";;
-  esac
-
-  if $CREATE_POSTGRES_USER; then
-    read -p "Enter the username: " username
-    if ! sudo -u postgres psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='$username'" | grep -q 1; then
-      sudo -u postgres createuser -s $username
-      sudo -u postgres createdb $username
-      sudo su - postgres -c "psql -c \"GRANT ALL PRIVILEGES ON DATABASE $username TO $username;\""
-    else
-      echo "PostgreSQL is already configured for $username user"
-    fi
-  fi
-fi
-
-# Check if fd symlink already exists before creating
-if [ ! -L /usr/local/bin/fd ]; then
-  ln -s "$(which fdfind)" /usr/local/bin/fd
-fi
-
-# Check if ctree is already installed before attempting to install
-if [[ "$uname" == "Linux" ]] ; then
-  dir=/usr/local/bin
-else
-  dir=/opt/
-fi
-
-if [ ! -d "$dir" ]; then
-  git clone git@github.com:shkrt/component_tree.git
-  sudo cp -R component_tree/ "$dir/component_tree"
-  sudo chmod a+x "$dir/component_tree/bin/ctree"
-  export PATH="$PATH:$dir/component_tree/bin"
-fi
-
-# Configure Nvim
-if ! command -v nvim &> /dev/null 2>&1; then
-  brew install neovim
-fi
-
-git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1
-ln -s ~/.config/nvim_custom ~/.config/nvim/lua/custom
-nvim
+done
